# Continuous Control

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the second project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Reacher.app"`
- **Windows** (x86): `"path/to/Reacher_Windows_x86/Reacher.exe"`
- **Windows** (x86_64): `"path/to/Reacher_Windows_x86_64/Reacher.exe"`
- **Linux** (x86): `"path/to/Reacher_Linux/Reacher.x86"`
- **Linux** (x86_64): `"path/to/Reacher_Linux/Reacher.x86_64"`
- **Linux** (x86, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86"`
- **Linux** (x86_64, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86_64"`

For instance, if you are using a Mac, then you downloaded `Reacher.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Reacher.app")
```

In [2]:
# env = UnityEnvironment(file_name='Reacher_One_Linux/Reacher.x86_64')
# env = UnityEnvironment(file_name='Reacher_Linux/Reacher.x86_64')
# env = UnityEnvironment(file_name='Reacher_Linux_NoVis/Reacher.x86_64')
env = UnityEnvironment(file_name='Reacher_Linux_One_NoVis/Reacher.x86_64')

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_size -> 5.0
		goal_speed -> 1.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, a double-jointed arm can move to target locations. A reward of `+0.1` is provided for each step that the agent's hand is in the goal location. Thus, the goal of your agent is to maintain its position at the target location for as many time steps as possible.

The observation space consists of `33` variables corresponding to position, rotation, velocity, and angular velocities of the arm.  Each action is a vector with four numbers, corresponding to torque applicable to two joints.  Every entry in the action vector must be a number between `-1` and `1`.

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 1
Size of each action: 4
There are 1 agents. Each observes a state with length: 33
The state for the first agent looks like: [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
  1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.75471878e+00 -1.00000000e+00
  5.55726671e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
 -1.68164849e-01]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [5]:
"""
env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
    actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    rewards = env_info.rewards                         # get reward (for each agent)
    dones = env_info.local_done                        # see if episode finished
    scores += env_info.rewards                         # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    if np.any(dones):                                  # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))
"""

"\nenv_info = env.reset(train_mode=False)[brain_name]     # reset the environment    \nstates = env_info.vector_observations                  # get the current state (for each agent)\nscores = np.zeros(num_agents)                          # initialize the score (for each agent)\nwhile True:\n    actions = np.random.randn(num_agents, action_size) # select an action (for each agent)\n    actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1\n    env_info = env.step(actions)[brain_name]           # send all actions to tne environment\n    next_states = env_info.vector_observations         # get next state (for each agent)\n    rewards = env_info.rewards                         # get reward (for each agent)\n    dones = env_info.local_done                        # see if episode finished\n    scores += env_info.rewards                         # update the score (for each agent)\n    states = next_states                               # roll over states to next ti

When finished, you can close the environment.

In [6]:
# Don't close the environment to use it for next experiments
# After close, it is impossible to reload environment on this Unity version.
# env.close()

### 4. Training method

This is implementation of training method for common: DDPG, PPO and others.

#### 4.1. Import modules

In [7]:
import time
import gym
import random
import torch
import numpy as np
from collections import deque
import matplotlib.pyplot as plt
%matplotlib inline

#### 4.2. Set device

In [8]:
# Set device between cuda:0 and cpu
torch_device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(torch_device)

cpu


#### 4.4 Define training method

In [9]:
def train(n_episodes=200, max_t=1000, agents=None, num_agents=20, filenames=None,
          benchmark_score=30, rolling_n_episodes=10):
    """Deep Q-Learning.
    
    Params
    ======
        n_episodes (int): maximum number of training episodes
        max_t (int): maximum number of timesteps per episode
        agents (obj): training agent instances
        num_agents (int): number of agents
        filenames (list): string of filenames to store weights of actor and critic
        benchmark_score (int): the score of agent should be over this score
        rolling_n_episodes (int): the score is checked whenever number of tries reachs to this
    """
    start_time = time.time()
        
    all_agent_scores = []                             # list containing scores from each episode for all agents
    scores_window = deque(maxlen=rolling_n_episodes)  # last rolling_n_episodes scores
    avg_checked = False
    
    for i_episode in range(1, n_episodes + 1):
        env_info = env.reset(train_mode=True)[brain_name]  # reset the environment
        states = env_info.vector_observations              # get the current state (for each agent)
        scores = np.zeros(num_agents)                      # initialize the score (for each agent)

        for agent in agents:                               # Reset agent before starting new episode
            agent.reset()

        for t in range(max_t):
            actions = [agent.act(states[i]) for i, agent in enumerate(agents)]  # select an action
            env_info = env.step(actions)[brain_name]       # send the action to the environment
            next_states = env_info.vector_observations     # get the next state
            rewards = env_info.rewards                     # get the reward
            dones = env_info.local_done                    # see if episode has finished

            for i, agent in enumerate(agents):
                agent.step(states[i], actions[i], rewards[i], next_states[i], dones[i])

            states = next_states                           # roll over the state to next time step
            scores += rewards                              # update the score
            if np.any(dones):                              # exit loop if episode finished
                break

        avg_score = np.mean(scores)                        # average score of all agents
        scores_window.append(avg_score)                    # save most recent score
        all_agent_scores.append(avg_score)                 # save most recent score
        avg_scores_window = np.mean(scores_window)         # get average score of current window
        
        print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, avg_scores_window), end="")
        
        if i_episode % rolling_n_episodes == 0:
            print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, avg_scores_window))
        
        if not avg_checked and avg_scores_window >= benchmark_score:
            print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(
                  i_episode - rolling_n_episodes, avg_scores_window))
            avg_checked = True

    print('\nTraining time = {:.2f}s'.format(time.time() - start_time))
    if filenames:
        agent.store_weights(filenames)

    return all_agent_scores

#### 4.5. Define plot score method

In [10]:
import pandas as pd

def plot_scores(scores, benchmark_score, rolling_n_episodes):
    # plot the scores
    fig = plt.figure()
    ax = fig.add_subplot(111)

    plt.plot(np.arange(len(scores)), scores)
    plt.ylabel('Score')
    plt.xlabel('Episode #')
    ax.axhline(benchmark_score, c="red", alpha=0.5)
    
    rolling_window = rolling_n_episodes
    rolling_mean = pd.Series(scores).rolling(rolling_window).mean()
    plt.plot(rolling_mean, c='yellow', alpha=0.7);
    
    plt.show()

#### 4.6. Hyper-parameters for replay buffer and noise

In [11]:
params = {
    'buffer_size': int(1e5),        # replay buffer size
    'batch_size': 128,              # minibatch size
    'seed': 0,                      # Seed to generate random numbers
}

#### 4.6. Create replay buffer

In [12]:
# Create replay buffer
from replaybuffer import ReplayBuffer

memory = ReplayBuffer(action_size, params['buffer_size'], params['batch_size'], params['seed'], torch_device)

#### 4.6 Test trained agent
Below codes executes on Windows.
It shows agents how to move by training result.

In [13]:
def test(agent, num_agents=20, max_t=1000):
    env_info = env.reset(train_mode=False)[brain_name] # reset the environment
    states = env_info.vector_observations              # get the current state
    scores = np.zeros(num_agents)

    for t in range(max_t):
        actions = agent.act(states)                    # select an action
        env_info = env.step(actions)[brain_name]       # send the action to the environment
        rewards = env_info.rewards                     # get the reward
        dones = env_info.local_done                    # see if episode has finished
        states = env_info.vector_observations          # roll over the state to next time step
        scores += rewards                              # update the score
        if np.any(dones):                              # exit loop if episode finished
            break
    
    print('Score: {:.2f}'.format(np.mean(scores)))

### 5. DDPG
This is implementation of DDPG.

#### 5.1. Set hyper-parameters

In [14]:
params = {
    'buffer_size': int(1e5),            # replay buffer size
    'batch_size': 128,                  # minibatch size
    'gamma': 0.99,                      # discount factor
    'tau': 1e-3,                        # for soft update of target parameters
    'update_every': 1,                  # update parameters per this number
    'lr_actor': 1e-4,                   # learning rate of the Actor
    'lr_critic': 1e-3,                  # learning rate of the Critic
    'seed': 0,                          # Seed to generate random numbers
    'hidden_layers_actor': [256, 128],  # Number of nodes in hidden layers of the Actor
    'hidden_layers_critic': [256, 128], # Number of nodes in hidden layers of the Critic
    'weight_decay': 0                   # L2 weight decay
}

#### 5.2. Set plot parameters

In [15]:
# Parameters to store and plot scores
rolling_n_episodes = 10     # Score is checked whenever number of tries reachs to this.
benchmark_score = 30.0      # Score of agent should be over this score

#### 5.3. Create agent

In [16]:
from ddpg_agent import DDPGAgent

ddpg_agents = [DDPGAgent(state_size, action_size, memory, torch_device, params)
               for _ in range(num_agents)]

#### 5.4. Training

In [17]:
ddpg_scores = train(200, 1000, ddpg_agents, num_agents, ["model_ddpg_actor.pth", "model_ddpg_critic.pth"],
                    benchmark_score, rolling_n_episodes)

tensor(1.00000e-02 *
       [[ 5.8628, -4.5580,  4.0546, -6.4301],
        [ 5.3254, -6.0295,  6.3995, -6.1332],
        [ 4.1949, -6.2753,  3.4617, -7.8963],
        [ 3.8729, -5.9856,  4.1496, -6.1413],
        [ 5.6561, -6.2139,  4.5591, -6.0884],
        [ 5.6837, -6.0531,  4.1263, -5.7515],
        [ 4.3011, -6.1205,  3.6771, -7.9846],
        [ 4.3097, -2.9508,  4.3672, -7.4294],
        [ 3.9992, -6.0453,  3.9760, -6.2625],
        [ 4.1200, -5.1365,  4.0856, -5.6841],
        [ 5.1205, -5.4640,  5.0833, -5.1779],
        [ 5.6868, -6.5862,  5.7096, -5.6727],
        [ 4.1402, -6.2156,  3.4623, -7.0212],
        [ 5.7752, -6.5851,  3.9144, -6.4457],
        [ 5.9554, -5.4402,  3.8359, -6.3741],
        [ 3.5997, -1.7014,  4.8436, -6.6632],
        [ 4.3888, -4.0332,  6.6762, -6.2871],
        [ 6.8174, -5.6165,  3.6862, -6.3167],
        [ 4.4427, -2.5325,  5.2685, -6.8720],
        [ 4.3027, -6.3782,  3.8107, -7.5593],
        [ 5.2423, -5.5088,  4.4185, -4.9977],
        [ 4.8

tensor([[ 0.7707,  0.4933,  0.8421,  0.7906],
        [ 0.4907,  0.4853,  0.7783,  0.6066],
        [ 0.7399,  0.6993,  0.6303,  0.6743],
        [ 0.4850,  0.5518,  0.6788,  0.3857],
        [ 0.5767,  0.4876,  0.6882,  0.6368],
        [ 0.5983,  0.4012,  0.9365,  0.7663],
        [ 0.4909,  0.4868,  0.5794,  0.3034],
        [ 0.5759,  0.6864,  0.8179,  0.5329],
        [ 0.7077,  0.5026,  0.7497,  0.4942],
        [ 0.6177,  0.5664,  0.7011,  0.5764],
        [ 0.6879,  0.5163,  0.7160,  0.6602],
        [ 0.7228,  0.7388,  0.5585,  0.6405],
        [ 0.6233,  0.5927,  0.6717,  0.5389],
        [ 0.6814,  0.6608,  0.8766,  0.5664],
        [ 0.5216,  0.4750,  0.7935,  0.6773],
        [ 0.8653,  0.5787,  0.6844,  0.6818],
        [ 0.7899,  0.4871,  0.7407,  0.5856],
        [ 0.8973,  0.6419,  0.6675,  0.7098],
        [ 0.5123,  0.4806,  0.6705,  0.4410],
        [ 0.9371,  0.6404,  0.5781,  0.4774],
        [ 0.7805,  0.6234,  0.9353,  0.6251],
        [ 0.8604,  0.5835,  0.6946

tensor(1.00000e-02 *
       [[ 4.9306, -3.6068,  4.4369, -7.1479],
        [ 5.9061, -4.5570,  4.0422, -6.4928],
        [ 3.8567, -5.4984,  4.1696, -5.8713],
        [ 4.7861, -3.7819,  4.4208, -6.1147],
        [ 5.0094, -6.4916,  6.2478, -6.4245],
        [ 5.3242, -6.0713,  6.7483, -6.3434],
        [ 3.7771, -5.5763,  4.1548, -5.9019],
        [ 6.7158, -4.9876,  4.0118, -7.0594],
        [ 4.0389, -1.6890,  5.1365, -7.0783],
        [ 3.5970, -1.4271,  4.9730, -6.8566],
        [ 4.8570, -4.2961,  4.9873, -5.7569],
        [ 5.5540, -6.5434,  4.3804, -7.5730],
        [ 4.0998, -6.0637,  3.4637, -8.0548],
        [ 4.7843, -5.3160,  7.1439, -6.4990],
        [ 5.2095, -4.8273,  6.1651, -6.3710],
        [ 4.5267, -5.7163,  6.5932, -6.1678],
        [ 4.6731, -6.1266,  4.3886, -8.1597],
        [ 6.4114, -4.1163,  4.0895, -6.6340],
        [ 4.8451, -5.8588,  3.8583, -6.9380],
        [ 4.5096, -6.2460,  4.6812, -7.9242],
        [ 4.9712, -6.2828,  3.8195, -6.1951],
        [ 4.6

tensor([[ 0.7864,  0.7875,  0.8352,  0.5461],
        [ 0.7954,  0.6041,  0.8353,  0.6317],
        [ 0.6777,  0.4776,  0.6515,  0.6079],
        [ 0.7738,  0.5174,  0.6562,  0.5141],
        [ 0.9489,  0.5170,  0.6104,  0.6498],
        [ 0.7107,  0.5760,  0.6032,  0.5876],
        [ 0.8495,  0.6132,  0.5711,  0.5957],
        [ 0.7805,  0.6234,  0.9353,  0.6251],
        [ 0.4595,  0.7131,  0.7866,  0.6105],
        [ 0.7635,  0.4899,  0.8995,  0.7111],
        [ 0.5252,  0.6995,  0.8924,  0.6370],
        [ 0.5613,  0.6679,  0.7561,  0.5180],
        [ 0.5425,  0.4707,  0.8011,  0.6633],
        [ 0.7491,  0.6358,  0.6544,  0.6343],
        [ 0.7162,  0.6771,  0.5669,  0.7063],
        [ 0.9317,  0.5382,  0.5534,  0.6292],
        [ 0.7432,  0.6750,  0.5948,  0.6694],
        [ 0.9392,  0.5992,  0.6953,  0.6895],
        [ 0.6682,  0.4280,  0.7904,  0.6710],
        [ 0.8093,  0.4450,  0.7297,  0.7243],
        [ 0.9208,  0.6681,  0.6874,  0.6210],
        [ 0.5759,  0.6864,  0.8179

tensor([[ 0.7539,  0.5499,  0.8080,  0.5898],
        [ 0.8925,  0.6352,  0.9891,  0.7084],
        [ 0.6871,  0.5010,  0.8498,  0.7117],
        [ 0.6682,  0.4280,  0.7904,  0.6710],
        [ 0.7712,  0.6015,  0.6627,  0.5914],
        [ 0.7228,  0.7388,  0.5585,  0.6405],
        [ 0.9420,  0.3985,  0.8651,  0.4677],
        [ 0.7780,  0.3536,  0.9128,  0.3566],
        [ 0.8705,  0.6443,  0.7867,  0.6142],
        [ 0.9291,  0.5438,  0.5405,  0.5173],
        [ 0.7571,  0.5190,  0.6642,  0.6912],
        [ 0.8509,  0.7358,  1.0000,  0.7268],
        [ 0.5216,  0.4750,  0.7935,  0.6773],
        [ 0.8196,  0.5712,  0.5943,  0.6778],
        [ 0.5635,  0.4402,  0.7625,  0.6530],
        [ 0.7060,  0.3925,  0.6764,  0.5141],
        [ 0.5863,  0.5840,  0.8004,  0.6220],
        [ 0.6442,  0.5947,  0.5957,  0.6780],
        [ 0.7843,  0.5733,  0.7011,  0.5478],
        [ 0.4850,  0.5518,  0.6788,  0.3857],
        [ 0.3463,  0.2440,  0.4159,  0.1337],
        [ 0.2114,  0.1006,  0.1243

tensor(1.00000e-02 *
       [[ 4.2403, -1.6113,  4.9748, -7.3787],
        [ 5.1764, -2.6864,  4.4643, -6.7645],
        [ 4.2387, -6.1484,  3.5956, -8.2839],
        [ 4.5964, -3.7076,  5.8185, -6.2239],
        [ 4.7763, -5.8638,  6.2484, -5.9897],
        [ 5.0308, -5.7010,  4.4018, -5.2262],
        [ 5.5046, -6.0886,  3.8864, -6.6740],
        [ 5.0249, -5.2429,  7.3063, -6.7594],
        [ 4.6510, -6.3241,  4.8249, -8.1626],
        [ 4.2960, -5.1104,  4.0442, -5.6789],
        [ 7.1172, -5.0311,  4.1009, -7.0754],
        [ 5.3741, -5.2975,  7.0948, -6.6629],
        [ 4.7270, -2.0829,  4.6139, -6.5665],
        [ 5.3232, -6.7467,  4.5053, -8.0508],
        [ 5.7856, -6.4727,  5.3374, -6.5931],
        [ 4.1784, -5.1494,  4.1136, -5.7578],
        [ 4.8201, -6.2041,  4.5377, -8.4117],
        [ 4.4679, -6.2399,  3.8296, -8.2704],
        [ 4.1222, -6.0023,  3.9465, -6.4485],
        [ 6.3062, -3.8244,  4.8445, -7.5126],
        [ 6.1329, -6.4185,  3.8570, -6.9837],
        [ 5.7

tensor([[ 0.2767,  0.0401,  0.3733, -0.3982],
        [ 0.2174,  0.0058,  0.2971, -0.3319],
        [ 0.2484,  0.0388,  0.3320, -0.3543],
        [ 0.1904, -0.0453,  0.2584, -0.3337],
        [ 0.3076,  0.0973,  0.3227, -0.3843],
        [ 0.2385,  0.0519,  0.2604, -0.3059],
        [ 0.3348,  0.1097,  0.3339, -0.4092],
        [ 0.1885, -0.0020,  0.2605, -0.3021],
        [ 0.2327, -0.0422,  0.2871, -0.3682],
        [ 0.1948, -0.0340,  0.2622, -0.3330],
        [ 0.2756, -0.0161,  0.2849, -0.3809],
        [ 0.2784,  0.0659,  0.2627, -0.3451],
        [ 0.1009, -0.0493,  0.1070, -0.1424],
        [ 0.3605,  0.0669,  0.3033, -0.4184],
        [ 0.1903, -0.0305,  0.2595, -0.3293],
        [ 0.2775, -0.0163,  0.2987, -0.4013],
        [ 0.2560,  0.0292,  0.3494, -0.3789],
        [ 0.2897,  0.0413,  0.2433, -0.3449],
        [ 0.2329, -0.0457,  0.2962, -0.3834],
        [ 0.2074,  0.0037,  0.2903, -0.3297],
        [ 0.3150,  0.0903,  0.3703, -0.4091],
        [ 0.3187,  0.0769,  0.2824

tensor([[ 0.9901,  0.6243,  1.0000,  0.1449],
        [ 0.8093,  0.4450,  0.7297,  0.7243],
        [ 0.6751,  0.4025,  0.8660,  0.4192],
        [ 0.4909,  0.4868,  0.5794,  0.3034],
        [ 0.5252,  0.6995,  0.8924,  0.6370],
        [ 0.8253,  0.7624,  0.7185,  0.6470],
        [ 0.8230,  0.5015,  0.5234,  0.7420],
        [ 0.5984,  0.5763,  0.6547,  0.5886],
        [ 0.5516,  0.4350,  0.8234,  0.7670],
        [ 0.6444,  0.6511,  0.7752,  0.4713],
        [ 0.9034,  0.5825,  1.0000,  0.2758],
        [ 0.8103,  0.6134,  0.7374,  0.5614],
        [ 0.5146,  0.7748,  0.7985,  0.5099],
        [ 0.4187,  0.7069,  0.8162,  0.6189],
        [ 0.6654,  0.5153,  0.6754,  0.8121],
        [ 0.9408,  0.5363,  0.6635,  0.7363],
        [ 0.7287,  0.7423,  0.7185,  0.5271],
        [ 0.3463,  0.2440,  0.4159,  0.1337],
        [ 0.8703,  0.4320,  0.6308,  0.6672],
        [ 0.7779,  0.6777,  0.6735,  0.5554],
        [ 0.8927,  0.7017,  0.8976,  0.7419],
        [ 0.8756,  0.3964,  0.8543

tensor([[ 0.2416,  0.0845,  0.3875, -0.3896],
        [ 0.2856,  0.0923,  0.4205, -0.4236],
        [ 0.1937,  0.0481,  0.3180, -0.3028],
        [ 0.3580,  0.0920,  0.4361, -0.4310],
        [ 0.3229,  0.1325,  0.5466, -0.5297],
        [ 0.1587, -0.0059,  0.1832, -0.1920],
        [ 0.3592,  0.1424,  0.4821, -0.4864],
        [ 0.2612,  0.1018,  0.4336, -0.4227],
        [ 0.3209,  0.1319,  0.5398, -0.5217],
        [ 0.4455,  0.1871,  0.4705, -0.5088],
        [ 0.4325,  0.1624,  0.4459, -0.4736],
        [ 0.3548,  0.0999,  0.4345, -0.4322],
        [ 0.4061,  0.1323,  0.4748, -0.4775],
        [ 0.3897,  0.1653,  0.5818, -0.5662],
        [ 0.4662,  0.1849,  0.4569, -0.4989],
        [ 0.2580,  0.0794,  0.3901, -0.3850],
        [ 0.4018,  0.1375,  0.4322, -0.4455],
        [ 0.1254, -0.0198,  0.1390, -0.1525],
        [ 0.4009,  0.1334,  0.4120, -0.4323],
        [ 0.2497,  0.0945,  0.4137, -0.4077],
        [ 0.2660,  0.0950,  0.4605, -0.4477],
        [ 0.3835,  0.1593,  0.5286

tensor(1.00000e-02 *
       [[ 5.5468, -5.3331,  4.9467, -5.3173],
        [ 5.2456, -1.8738,  5.0611, -7.1245],
        [ 4.3611, -5.0924,  4.1567, -5.8140],
        [ 6.1199, -6.1072,  5.1734, -6.8269],
        [ 4.4367, -1.5081,  4.8389, -7.2338],
        [ 5.2939, -4.1077,  5.5012, -6.3269],
        [ 4.2800, -6.0600,  4.2834, -6.6441],
        [ 4.4565, -1.2682,  4.9652, -7.7283],
        [ 3.9015, -5.7180,  4.4226, -6.2582],
        [ 5.4649, -3.0185,  5.9526, -7.4130],
        [ 5.9402, -5.8190,  7.5306, -7.2084],
        [ 5.5522, -6.6042,  5.0590, -7.6081],
        [ 6.6167, -6.0129,  4.0997, -7.3298],
        [ 7.3773, -5.4438,  4.1212, -6.9049],
        [ 6.0922, -6.3136,  5.2647, -8.6308],
        [ 7.1347, -4.8497,  4.2249, -6.9774],
        [ 5.5470, -1.8469,  5.2303, -7.4060],
        [ 4.6153, -5.9791,  4.1917, -6.0784],
        [ 5.6576, -6.2141,  7.1379, -7.2522],
        [ 5.4839, -5.1336,  6.8151, -6.2744],
        [ 5.1587, -5.6428,  4.6211, -5.4395],
        [ 5.5

tensor([[ 0.4360,  0.2404,  0.5763, -0.4979],
        [ 0.4952,  0.2086,  0.5820, -0.5776],
        [ 0.4403,  0.2045,  0.6650, -0.6088],
        [ 0.6027,  0.2783,  0.6164, -0.6155],
        [ 0.5885,  0.3101,  0.6062, -0.5084],
        [ 0.5880,  0.3202,  0.6382, -0.5262],
        [ 0.2878,  0.0886,  0.3255, -0.2630],
        [ 0.6205,  0.3081,  0.6680, -0.6688],
        [ 0.5755,  0.3011,  0.6316, -0.5154],
        [ 0.5744,  0.3084,  0.6143, -0.5058],
        [ 0.4063,  0.1889,  0.6343, -0.5839],
        [ 0.2347,  0.0790,  0.3308, -0.2829],
        [ 0.5977,  0.2774,  0.6333, -0.6318],
        [ 0.6113,  0.3366,  0.6493, -0.5417],
        [ 0.5162,  0.2153,  0.7149, -0.6733],
        [ 0.6320,  0.3322,  0.6035, -0.5742],
        [ 0.5516,  0.2857,  0.5896, -0.4862],
        [ 0.6409,  0.3185,  0.6282, -0.6228],
        [ 0.5977,  0.3144,  0.5840, -0.5172],
        [ 0.4869,  0.2395,  0.7265, -0.6776],
        [ 0.4677,  0.2433,  0.7029, -0.6504],
        [ 0.5495,  0.2521,  0.5559

tensor(1.00000e-02 *
       [[ 6.8001, -5.5254,  4.7943, -7.0213],
        [ 7.7191, -5.2237,  4.4458, -7.1916],
        [ 5.1732, -3.9925,  7.4492, -7.4696],
        [ 5.0015, -6.1448,  4.4438, -8.9328],
        [ 5.4870, -5.3684,  4.5449, -6.9852],
        [ 6.1856, -5.6789,  7.9786, -7.5989],
        [ 5.3170, -5.6094,  4.8316, -7.2969],
        [ 5.5563, -2.8784,  5.9575, -7.0065],
        [ 5.2312, -5.9395,  5.2457, -8.8481],
        [ 7.6343, -5.0361,  5.0186, -7.5086],
        [ 5.4877, -4.6688,  6.2166, -6.3788],
        [ 5.9556, -3.1744,  5.2135, -8.1652],
        [ 6.1499, -5.7648,  4.5767, -7.3625],
        [ 7.8914, -4.5074,  4.8885, -8.2504],
        [ 5.5607, -2.0497,  6.4057, -8.1854],
        [ 5.2697, -2.3643,  4.9288, -8.1430],
        [ 4.0221, -5.6585,  4.5479, -6.3468],
        [ 5.2747, -5.6184,  7.1159, -6.8276],
        [ 4.9532, -6.2631,  5.0870, -8.4503],
        [ 5.2141, -3.4227,  6.7363, -7.1240],
        [ 5.3117, -5.3731,  7.6796, -7.3311],
        [ 5.6

tensor(1.00000e-02 *
       [[ 7.8241, -4.2254,  5.3794, -8.7014],
        [ 7.0023, -5.0846,  5.0385, -7.2848],
        [ 5.8161, -4.8469,  8.6125, -8.0425],
        [ 6.2309, -5.4898,  6.8428, -6.8870],
        [ 6.3430, -5.6393,  4.7629, -7.4900],
        [ 8.0955, -3.8104,  5.2532, -7.9372],
        [ 4.5409, -5.9024,  4.4639, -6.8461],
        [ 6.1548, -6.1646,  6.3219, -8.9552],
        [ 5.8207, -3.3973,  8.1278, -8.2132],
        [ 5.4967, -2.8109,  5.0928, -7.6344],
        [ 5.4640, -5.3105,  7.9256, -7.5575],
        [ 6.5909, -6.2063,  6.9972, -6.9815],
        [ 5.1677, -1.0481,  5.5010, -7.7306],
        [ 5.5981, -4.6242,  6.3899, -6.5304],
        [ 5.0012, -1.1350,  6.0808, -8.1767],
        [ 6.2385, -5.7361,  4.5937, -6.3274],
        [ 6.3571, -5.8228,  5.0469, -6.7267],
        [ 6.0462, -3.5198,  7.8392, -8.2856],
        [ 5.5542, -6.2626,  5.7145, -8.4425],
        [ 7.2847, -5.1750,  4.7393, -7.2686],
        [ 4.4807, -5.0452,  4.2840, -5.9187],
        [ 6.3

tensor(1.00000e-02 *
       [[ 7.4826, -2.9262,  5.6500, -7.9919],
        [ 5.8144, -5.1767,  5.4060, -5.6610],
        [ 6.3728, -5.8397,  6.0532, -9.0940],
        [ 4.6527, -5.8362,  4.5763, -6.9051],
        [ 5.6417, -2.2198,  5.3415, -8.5285],
        [ 8.5584, -4.2579,  5.3163, -8.3214],
        [ 6.2232, -6.1446,  6.6113, -8.0215],
        [ 5.7910, -2.5244,  5.8114, -7.8511],
        [ 5.8852, -5.6275,  5.8269, -9.4230],
        [ 6.4114, -5.8522,  6.9889, -6.7958],
        [ 8.3763, -4.8746,  5.0524, -7.8793],
        [ 6.7731, -2.5846,  6.1721, -8.2213],
        [ 7.9957, -4.7005,  5.0787, -7.4246],
        [ 6.7509, -6.1278,  7.2498, -7.1865],
        [ 6.4715, -5.8867,  8.1171, -7.8904],
        [ 5.0454, -1.3354,  5.8778, -7.9827],
        [ 6.5068, -6.0322,  6.6759, -7.7921],
        [ 5.1999, -1.2189,  5.5961, -7.9933],
        [ 4.5274, -5.7902,  4.8212, -6.7362],
        [ 6.6272, -2.0706,  5.6459, -8.0830],
        [ 5.7867, -6.5709,  6.4456, -8.2437],
        [ 5.1

tensor(1.00000e-02 *
       [[ 8.4427, -4.6975,  5.3871, -7.7422],
        [ 5.6256, -5.9782,  5.2916, -8.5807],
        [ 6.3263, -5.6303,  5.8715, -9.6982],
        [ 6.2272, -4.7169,  9.2166, -8.5979],
        [ 5.7847, -5.9496,  5.8986, -8.9607],
        [ 5.6805, -5.5810,  5.4704, -8.7676],
        [ 8.2889, -3.2721,  5.5038, -8.2411],
        [ 5.8665, -5.7286,  4.7516, -6.9476],
        [ 6.2281, -6.0537,  6.7401, -8.1958],
        [ 6.1306, -0.7963,  6.7568, -9.2585],
        [ 6.1803, -3.4566,  6.9837, -7.6784],
        [ 8.5009, -4.7076,  5.1371, -7.6621],
        [ 6.7959, -1.3410,  6.3046, -8.4280],
        [ 5.9607, -5.9224,  7.0133, -7.4140],
        [ 4.4938, -5.0550,  4.5228, -6.1165],
        [ 7.1663, -5.6083,  6.3996, -9.3119],
        [ 4.2920, -5.4122,  4.6598, -6.3313],
        [ 6.6840, -5.8272,  5.9741, -7.6654],
        [ 7.7864, -2.7974,  5.8864, -8.1911],
        [ 7.6904, -2.4531,  6.2214, -8.7615],
        [ 6.0268, -5.4644,  5.0160, -7.0549],
        [ 5.3

KeyboardInterrupt: 

#### 5.5. plot scores

In [ ]:
plot_scores(ddpg_scores, benchmark_score, rolling_n_episodes)

#### 5.6. Test

In [ ]:
test(ddpg_agent, num_agents)